# Generated by Django 2.2.6 on 2019-10-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='small_image_url',
            field=models.TextField(),
        ),
    ]
