# Generated by Django 2.2.6 on 2019-10-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191021_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='capas'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(),
        ),
    ]
