# Generated by Django 2.2.6 on 2019-10-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191023_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
