# Generated by Django 2.2.6 on 2019-10-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191024_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_file',
        ),
    ]
