# Generated by Django 2.2.6 on 2019-11-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191031_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='book_id',
            new_name='book',
        ),
    ]
