# Generated by Django 2.2.6 on 2019-11-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191031_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='book',
        ),
    ]
